# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target "VideoUpload" do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod "Alamofire","~> 4.9.1"
    pod "Moya","~> 13.0.1"
    pod "SwiftyJSON"
  pod "QCloudCOSXML" # 对象存储

end
